// Household onboarding logic: create or join a household and set the weather
// location. Pure TypeScript with an injected gateway so it is unit-tested
// without React Native or a network (see tests/household.test.ts).

export const MAX_HOUSEHOLD_NAME_LENGTH = 60;
export const MAX_LOCATION_LENGTH = 100;
// Invite codes are generated by the database as 8 hex characters.
const INVITE_CODE_PATTERN = /^[0-9a-f]{8}$/;

export interface GatewayError {
  message: string;
}

export interface GatewayResult<T> {
  data: T | null;
  error: GatewayError | null;
}

export interface ProfileRow {
  household_id: string | null;
  name: string;
  location: string | null;
}

export interface HouseholdRow {
  id: string;
  name: string;
  invite_code: string;
}

export interface HouseholdGateway {
  createHousehold(name: string): Promise<GatewayResult<string>>;
  joinHousehold(inviteCode: string): Promise<GatewayResult<string>>;
  loadProfile(): Promise<GatewayResult<ProfileRow>>;
  updateLocation(location: string): Promise<GatewayResult<unknown>>;
  loadHousehold(householdId: string): Promise<GatewayResult<HouseholdRow>>;
}

export type OnboardingStep = "household" | "location" | "ready";

export type Result<T> = { ok: true; value: T } | { ok: false; error: string };

const NETWORK_ERROR = "Could not reach the server. Check your connection and try again.";

export function validateHouseholdName(name: string): string | null {
  const value = name.trim();
  if (value === "") return "Enter a name for your household.";
  if (value.length > MAX_HOUSEHOLD_NAME_LENGTH) {
    return `Household name must be at most ${MAX_HOUSEHOLD_NAME_LENGTH} characters.`;
  }
  return null;
}

export function normalizeInviteCode(code: string): string {
  return code.trim().toLowerCase();
}

export function validateInviteCode(code: string): string | null {
  const value = normalizeInviteCode(code);
  if (value === "") return "Enter the invite code.";
  if (!INVITE_CODE_PATTERN.test(value)) return "Invite codes are 8 letters and numbers, like 3fa91c0b.";
  return null;
}

export function validateLocation(location: string): string | null {
  const value = location.trim();
  if (value === "") return "Enter your city or ZIP code.";
  if (value.length > MAX_LOCATION_LENGTH) return `Location must be at most ${MAX_LOCATION_LENGTH} characters.`;
  return null;
}

export function friendlyHouseholdError(message: string): string {
  const text = message.toLowerCase();
  if (text.includes("invalid invite code")) return "That invite code was not found. Check it and try again.";
  if (text.includes("jwt") || text.includes("not authenticated")) return "Your session expired. Please sign in again.";
  return message;
}

// What the signed-in user still has to do before the app is usable.
export function onboardingStep(profile: Pick<ProfileRow, "household_id" | "location">): OnboardingStep {
  if (!profile.household_id) return "household";
  if (!profile.location || profile.location.trim() === "") return "location";
  return "ready";
}

async function guarded<T>(
  call: () => Promise<GatewayResult<T>>,
  emptyMessage = "The server returned no data. Please try again.",
): Promise<Result<T>> {
  try {
    const { data, error } = await call();
    if (error) return { ok: false, error: friendlyHouseholdError(error.message) };
    if (data === null || data === undefined) return { ok: false, error: emptyMessage };
    return { ok: true, value: data };
  } catch {
    return { ok: false, error: NETWORK_ERROR };
  }
}

export async function createHousehold(gateway: HouseholdGateway, name: string): Promise<Result<string>> {
  const problem = validateHouseholdName(name);
  if (problem) return { ok: false, error: problem };
  return guarded(() => gateway.createHousehold(name.trim()));
}

export async function joinHousehold(gateway: HouseholdGateway, inviteCode: string): Promise<Result<string>> {
  const problem = validateInviteCode(inviteCode);
  if (problem) return { ok: false, error: problem };
  return guarded(() => gateway.joinHousehold(normalizeInviteCode(inviteCode)));
}

export async function saveLocation(gateway: HouseholdGateway, location: string): Promise<Result<string>> {
  const problem = validateLocation(location);
  if (problem) return { ok: false, error: problem };
  const trimmed = location.trim();
  const saved = await guarded(async () => {
    const res = await gateway.updateLocation(trimmed);
    return { data: res.error ? null : true, error: res.error };
  });
  return saved.ok ? { ok: true, value: trimmed } : saved;
}

export interface Overview {
  profile: ProfileRow;
  household: HouseholdRow | null;
  step: OnboardingStep;
}

export async function loadOverview(gateway: HouseholdGateway): Promise<Result<Overview>> {
  const profile = await guarded(() => gateway.loadProfile(), "Your profile could not be found. Log out and sign in again.");
  if (!profile.ok) return profile;
  const householdId = profile.value.household_id;
  if (!householdId) {
    return { ok: true, value: { profile: profile.value, household: null, step: onboardingStep(profile.value) } };
  }
  const household = await guarded(() => gateway.loadHousehold(householdId), "Your household could not be found.");
  if (!household.ok) return household;
  return { ok: true, value: { profile: profile.value, household: household.value, step: onboardingStep(profile.value) } };
}
