// Profile and household logic: set the weather location, and optionally create,
// join or leave a household to share closets (D18). Pure TypeScript with an
// injected gateway so it is unit-tested without React Native or a network
// (see tests/household.test.ts).

export const MAX_HOUSEHOLD_NAME_LENGTH = 60;
export const MAX_LOCATION_LENGTH = 100;
// Invite codes are generated by the database as 8 hex characters.
const INVITE_CODE_PATTERN = /^[0-9a-f]{8}$/;

export interface GatewayError {
  message: string;
}

export interface GatewayResult<T> {
  data: T | null;
  error: GatewayError | null;
}

export interface ProfileRow {
  id: string;
  household_id: string | null;
  name: string;
  location: string | null;
}

export interface HouseholdRow {
  id: string;
  name: string;
  invite_code: string;
}

export interface MemberRow {
  id: string;
  name: string;
}

export interface HouseholdGateway {
  createHousehold(name: string): Promise<GatewayResult<string>>;
  joinHousehold(inviteCode: string): Promise<GatewayResult<string>>;
  leaveHousehold(): Promise<GatewayResult<unknown>>;
  loadProfile(): Promise<GatewayResult<ProfileRow>>;
  // Creates the signed-in user's own profile row if it is missing (see migration 0004).
  ensureProfile(): Promise<GatewayResult<unknown>>;
  updateLocation(location: string): Promise<GatewayResult<unknown>>;
  loadHousehold(householdId: string): Promise<GatewayResult<HouseholdRow>>;
  loadMembers(householdId: string): Promise<GatewayResult<MemberRow[]>>;
}

// A household is optional (D18), so onboarding only asks for the location.
export type OnboardingStep = "location" | "ready";

export type Result<T> = { ok: true; value: T } | { ok: false; error: string };

const NETWORK_ERROR = "Could not reach the server. Check your connection and try again.";

export function validateHouseholdName(name: string): string | null {
  const value = name.trim();
  if (value === "") return "Enter a name for your household.";
  if (value.length > MAX_HOUSEHOLD_NAME_LENGTH) {
    return `Household name must be at most ${MAX_HOUSEHOLD_NAME_LENGTH} characters.`;
  }
  return null;
}

export function normalizeInviteCode(code: string): string {
  return code.trim().toLowerCase();
}

export function validateInviteCode(code: string): string | null {
  const value = normalizeInviteCode(code);
  if (value === "") return "Enter the invite code.";
  if (!INVITE_CODE_PATTERN.test(value)) return "Invite codes are 8 letters and numbers, like 3fa91c0b.";
  return null;
}

export function validateLocation(location: string): string | null {
  const value = location.trim();
  if (value === "") return "Enter your city or ZIP code.";
  if (value.length > MAX_LOCATION_LENGTH) return `Location must be at most ${MAX_LOCATION_LENGTH} characters.`;
  return null;
}

export function friendlyHouseholdError(message: string): string {
  const text = message.toLowerCase();
  if (text.includes("invalid invite code")) return "That invite code was not found. Check it and try again.";
  if (text.includes("already in a household")) return "Leave your current household before joining or creating another.";
  if (text.includes("not in a household")) return "You are not in a household.";
  if (text.includes("jwt") || text.includes("not authenticated")) return "Your session expired. Please sign in again.";
  return message;
}

// What the signed-in user still has to do before the app is usable.
export function onboardingStep(profile: Pick<ProfileRow, "location">): OnboardingStep {
  if (!profile.location || profile.location.trim() === "") return "location";
  return "ready";
}

async function guarded<T>(
  call: () => Promise<GatewayResult<T>>,
  emptyMessage = "The server returned no data. Please try again.",
): Promise<Result<T>> {
  try {
    const { data, error } = await call();
    if (error) return { ok: false, error: friendlyHouseholdError(error.message) };
    if (data === null || data === undefined) return { ok: false, error: emptyMessage };
    return { ok: true, value: data };
  } catch {
    return { ok: false, error: NETWORK_ERROR };
  }
}

export async function createHousehold(gateway: HouseholdGateway, name: string): Promise<Result<string>> {
  const problem = validateHouseholdName(name);
  if (problem) return { ok: false, error: problem };
  return guarded(() => gateway.createHousehold(name.trim()));
}

export async function joinHousehold(gateway: HouseholdGateway, inviteCode: string): Promise<Result<string>> {
  const problem = validateInviteCode(inviteCode);
  if (problem) return { ok: false, error: problem };
  return guarded(() => gateway.joinHousehold(normalizeInviteCode(inviteCode)));
}

// For calls whose success carries no data (an update or a void RPC).
async function done(call: () => Promise<GatewayResult<unknown>>): Promise<Result<true>> {
  return guarded(async () => {
    const res = await call();
    return { data: res.error ? null : (true as const), error: res.error };
  });
}

export async function saveLocation(gateway: HouseholdGateway, location: string): Promise<Result<string>> {
  const problem = validateLocation(location);
  if (problem) return { ok: false, error: problem };
  const trimmed = location.trim();
  const saved = await done(() => gateway.updateLocation(trimmed));
  return saved.ok ? { ok: true, value: trimmed } : saved;
}

// Stops sharing closets. The user's garments stay theirs; the database deletes
// the household when the last member leaves.
export async function leaveHousehold(gateway: HouseholdGateway): Promise<Result<true>> {
  return done(() => gateway.leaveHousehold());
}

export interface Overview {
  profile: ProfileRow;
  household: HouseholdRow | null;
  // Everyone in the household, including the signed-in user; empty without a household.
  members: MemberRow[];
  step: OnboardingStep;
}

const MISSING_PROFILE = "Your profile could not be found. Log out and sign in again.";

// A missing profile row (deleted, or the account predates the sign-up trigger) is repaired once, never in a loop.
async function loadProfileOrCreate(gateway: HouseholdGateway): Promise<Result<ProfileRow>> {
  try {
    const first = await gateway.loadProfile();
    if (first.error) return { ok: false, error: friendlyHouseholdError(first.error.message) };
    if (first.data) return { ok: true, value: first.data };

    const created = await gateway.ensureProfile();
    if (created.error) return { ok: false, error: friendlyHouseholdError(created.error.message) };

    const second = await gateway.loadProfile();
    if (second.error) return { ok: false, error: friendlyHouseholdError(second.error.message) };
    return second.data ? { ok: true, value: second.data } : { ok: false, error: MISSING_PROFILE };
  } catch {
    return { ok: false, error: NETWORK_ERROR };
  }
}

export async function loadOverview(gateway: HouseholdGateway): Promise<Result<Overview>> {
  const profile = await loadProfileOrCreate(gateway);
  if (!profile.ok) return profile;
  const step = onboardingStep(profile.value);
  const householdId = profile.value.household_id;
  if (!householdId) {
    return { ok: true, value: { profile: profile.value, household: null, members: [], step } };
  }
  const household = await guarded(() => gateway.loadHousehold(householdId), "Your household could not be found.");
  if (!household.ok) return household;
  const members = await guarded(() => gateway.loadMembers(householdId));
  if (!members.ok) return members;
  return { ok: true, value: { profile: profile.value, household: household.value, members: members.value, step } };
}
