// Generates docs/m2-coverage.md for the Milestone 2 feature (auth + household).
// Usage: npm run coverage:report   (runs the whole suite, then summarizes the feature files only)
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const FEATURE_FILES = ["frontend/src/services/auth.ts", "frontend/src/services/household.ts"];
const FEATURE_TESTS = ["tests/auth.test.ts", "tests/household.test.ts"];
const THRESHOLD = 80;

execSync("npx vitest run --coverage --reporter=json --outputFile=coverage/results.json", { stdio: "inherit" });

type Metric = { total: number; covered: number; pct: number };
type Entry = { lines: Metric; statements: Metric; functions: Metric; branches: Metric };
const summary = JSON.parse(readFileSync("coverage/coverage-summary.json", "utf8")) as Record<string, Entry>;
const results = JSON.parse(readFileSync("coverage/results.json", "utf8")) as {
  numTotalTests: number;
  numPassedTests: number;
  testResults: { name: string; assertionResults: unknown[] }[];
};

const norm = (p: string) => p.replace(/\\/g, "/");
const entryFor = (file: string): Entry => {
  const key = Object.keys(summary).find((k) => norm(k).endsWith(file));
  if (!key) throw new Error(`no coverage data for ${file} (is it in vitest coverage.include?)`);
  return summary[key]!;
};

const kinds = ["lines", "statements", "functions", "branches"] as const;
const pct = (covered: number, total: number) => (total === 0 ? 100 : Math.round((covered / total) * 10_000) / 100);
const rows = FEATURE_FILES.map((file) => ({ file, e: entryFor(file) }));
const totals = Object.fromEntries(
  kinds.map((k) => {
    const covered = rows.reduce((n, r) => n + r.e[k].covered, 0);
    const total = rows.reduce((n, r) => n + r.e[k].total, 0);
    return [k, { covered, total, pct: pct(covered, total) }];
  }),
) as Record<(typeof kinds)[number], Metric>;

const testCount = (file: string) =>
  results.testResults.find((t) => norm(t.name).endsWith(file))?.assertionResults.length ?? 0;
const failing = results.numTotalTests - results.numPassedTests;
const lowest = Math.min(...kinds.map((k) => totals[k].pct));

const md = `# Milestone 2 test coverage analysis

Feature: **auth + household** (sign up / log in / log out, create or join a household, set the weather location).

Generated by \`npm run coverage:report\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand; re-run the command.

## Result

Every metric over the feature's code is **${lowest >= THRESHOLD ? "above" : "BELOW"} the ${THRESHOLD}% requirement** (lowest: ${lowest}%). Tests: ${results.numPassedTests} of ${results.numTotalTests} pass${failing > 0 ? ` (${failing} FAILING)` : ""} across the whole suite; ${FEATURE_TESTS.map((f) => `\`${f}\` has ${testCount(f)}`).join(", ")}.

| Feature file | Lines | Statements | Functions | Branches |
|---|---|---|---|---|
${rows.map((r) => `| \`${r.file}\` | ${kinds.map((k) => `${r.e[k].pct}% (${r.e[k].covered}/${r.e[k].total})`).join(" | ")} |`).join("\n")}
| **All feature files** | ${kinds.map((k) => `**${totals[k].pct}%** (${totals[k].covered}/${totals[k].total})`).join(" | ")} |

## How to reproduce

\`\`\`
npm ci
npm run coverage:report
\`\`\`

Tool: Vitest with the V8 coverage provider. Raw output goes to \`coverage/\` (git-ignored). CI also enforces an ${THRESHOLD}% threshold on all gated code (\`vitest.config.ts\`).

## What the tests cover

- Input validation: email, password, name, household name, invite code (trimming, case, boundaries).
- Every success and failure path of sign-up, log-in and log-out, with the server replaced by an in-memory fake, including the "confirm your email" case.
- Household flow: create household, join with an invite code (code normalized, bad-code message), load the profile and household, save name and location (blank location stored as empty).
- Queries are scoped to the signed-in user's own row and to the right household id, and RPC names and argument names match the database functions.
- Error mapping to friendly messages, and network failures.
- The suite was also checked by deliberately breaking the code (about 20 variants, including removing the user-id filter from updates): every real defect made at least one test fail.

## What is not covered, and why

- React Native screens (\`AuthScreen\`, \`HomeScreen\`, \`HouseholdScreen\`, \`App.tsx\`) and the hooks \`useSession\` and \`useProfile\` are not unit-tested: they need a device or emulator. They contain no business logic; the logic lives in the files above. Sign-up and log-in were verified by hand in Expo Go.
- \`frontend/src/services/supabase.ts\` (real client construction and the typed cast) is not covered for the same reason.
- No test talks to a real Supabase project; the database functions and row-level security in \`supabase/migrations/0001_init.sql\` are checked only for consistency with the tag schema, not executed.
`;

mkdirSync("docs", { recursive: true });
writeFileSync("docs/m2-coverage.md", md);
console.log(`\nWrote docs/m2-coverage.md (feature lowest metric: ${lowest}%)`);
if (lowest < THRESHOLD || failing > 0) process.exit(1);
