// Generates docs/m2-coverage.md for the Milestone 2 feature (auth + household).
// Usage: npm run coverage:report   (runs the whole suite, then summarizes the feature files only)
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const FEATURE_FILES = [
  "frontend/src/services/auth.ts",
  "frontend/src/services/household.ts",
  "frontend/src/services/householdGateway.ts",
];
const FEATURE_TESTS = ["tests/auth.test.ts", "tests/household.test.ts"];
const THRESHOLD = 80;

execSync("npx vitest run --coverage --reporter=json --outputFile=coverage/results.json", { stdio: "inherit" });

type Metric = { total: number; covered: number; pct: number };
type Entry = { lines: Metric; statements: Metric; functions: Metric; branches: Metric };
const summary = JSON.parse(readFileSync("coverage/coverage-summary.json", "utf8")) as Record<string, Entry>;
const results = JSON.parse(readFileSync("coverage/results.json", "utf8")) as {
  numTotalTests: number;
  numPassedTests: number;
  testResults: { name: string; assertionResults: unknown[] }[];
};

const norm = (p: string) => p.replace(/\\/g, "/");
const entryFor = (file: string): Entry => {
  const key = Object.keys(summary).find((k) => norm(k).endsWith(file));
  if (!key) throw new Error(`no coverage data for ${file} (is it in vitest coverage.include?)`);
  return summary[key]!;
};

const kinds = ["lines", "statements", "functions", "branches"] as const;
const pct = (covered: number, total: number) => (total === 0 ? 100 : Math.round((covered / total) * 10_000) / 100);
const rows = FEATURE_FILES.map((file) => ({ file, e: entryFor(file) }));
const totals = Object.fromEntries(
  kinds.map((k) => {
    const covered = rows.reduce((n, r) => n + r.e[k].covered, 0);
    const total = rows.reduce((n, r) => n + r.e[k].total, 0);
    return [k, { covered, total, pct: pct(covered, total) }];
  }),
) as Record<(typeof kinds)[number], Metric>;

const testCount = (file: string) =>
  results.testResults.find((t) => norm(t.name).endsWith(file))?.assertionResults.length ?? 0;
const failing = results.numTotalTests - results.numPassedTests;
const lowest = Math.min(...kinds.map((k) => totals[k].pct));

const md = `# Milestone 2 test coverage analysis

Feature: **auth + household** (sign up / log in / log out, set the weather location, and optionally create, join or leave a household to share closets).

Generated by \`npm run coverage:report\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand; re-run the command.

## Result

Every metric over the feature's code is **${lowest >= THRESHOLD ? "above" : "BELOW"} the ${THRESHOLD}% requirement** (lowest: ${lowest}%). Tests: ${results.numPassedTests} of ${results.numTotalTests} pass${failing > 0 ? ` (${failing} FAILING)` : ""} across the whole suite; ${FEATURE_TESTS.map((f) => `\`${f}\` has ${testCount(f)}`).join(", ")}.

| Feature file | Lines | Statements | Functions | Branches |
|---|---|---|---|---|
${rows.map((r) => `| \`${r.file}\` | ${kinds.map((k) => `${r.e[k].pct}% (${r.e[k].covered}/${r.e[k].total})`).join(" | ")} |`).join("\n")}
| **All feature files** | ${kinds.map((k) => `**${totals[k].pct}%** (${totals[k].covered}/${totals[k].total})`).join(" | ")} |

## How to reproduce

\`\`\`
npm ci
npm run coverage:report
\`\`\`

Tool: Vitest with the V8 coverage provider. Raw output goes to \`coverage/\` (git-ignored). CI also enforces an ${THRESHOLD}% threshold on all gated code (\`vitest.config.ts\`).

## What the tests cover

- Input validation (email, name, household name, invite code, location) including boundaries and malicious-looking input; every sign-up password rule (length 8–72, uppercase, lowercase, number, symbol), and that log-in keeps the basic rule so older accounts still work.
- Every success and failure path of sign-up, log-in, log-out, create household, join household, leave household, save location and overview loading (including the members list), with the server replaced by an in-memory fake.
- The onboarding state machine: location, then ready; a household is optional.
- The Supabase adapter: correct RPC names and argument names, queries scoped to the signed-in user's own row, errors never returning data.
- Error mapping to friendly messages, and network failures.

## What is not covered, and why

- React Native screens (\`AuthScreen\`, \`HomeScreen\`, household screens) and \`useSession\` are not unit-tested: they need a device or emulator. They contain no business logic; the logic lives in the files above.
- \`frontend/src/services/supabase.ts\` (real client construction) is not covered for the same reason.
- No test talks to a real Supabase project. \`tests/migration.test.ts\` checks the SQL text of both migrations (tag lists, RLS on every table, owner-only write policies, \`leave_household\`). The migrations were also executed once by hand on in-memory Postgres (PGlite) with stand-ins for Supabase's \`auth\` and \`storage\` schemas, exercising sharing, leaving and permissions as real users; that check is not part of the automated suite.
`;

mkdirSync("docs", { recursive: true });
writeFileSync("docs/m2-coverage.md", md);
console.log(`\nWrote docs/m2-coverage.md (feature lowest metric: ${lowest}%)`);
if (lowest < THRESHOLD || failing > 0) process.exit(1);
